### PR TITLE
[LYFT][STRMCMP-1143] Add an S3 connector for the beam python SDK

### PR DESCRIPTION
**Pull request by glaksh100**
This PR adds a separate S3 connector (with a corresponding translation layer in the `LyftFlinkStreamingPortableTranslations`). This is based on the [S3EventSource](https://github.com/lyft/streamingplatform/blob/master/spflinkjava/streamingplatform-events-source/src/main/java/com/lyft/streamingplatform/eventssource/S3EventSource.java).

An example Beam Python pipeline using the S3 source can be found [here](https://github.com/lyft/streamperfbench/blob/eae7587dfa3ad174351b908113c118a12791f2e9/beamperfk8s/beamperf/s3_source_pipeline.py). This has been tested with the [beamperfk8s3](http://beamperfk8s3.ingress.semistateful-prod-0.us-east-1.k8s.lyft.net/#/overview) job.

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by maghamravi** [comment]
The changes look good !  

However, I want to run by the idea of leveraging `LyftFlinkStreamingPortableTranslations#translateS3AndKinesisInputs` internally from `s3.py` with the conditional checks in LyftFlinkStreamingPortableTranslations and the Event connector to promote code reuse.

Keeping the two separate seem sensible for now but am foreseeing changes like https://jira.lyft.net/browse/STRMCMP-1126 that will force us to duplicate code :(

**Comment by glaksh100** [comment]
If I understand the recommendation correctly, it would imply`translateS3AndKinesisInputs` has a conditional check (maybe based on whether the `kinesisConfig` is passed or not) and keep `s3.py` as is? 

I think that's a reasonable change and I'm open to making it. My concern with that is, we'll always be tightly coupled with the user config being the same for _just_ S3 and the bootstrapping usecase. Even though that's the current assumption in `translateS3Inputs` right now, we can choose to evolve our S3 source differently from the bootstrapping API usecase in the future if needed. So, my preference is to keep them separate and maybe we could make the code even more DRY by abstracting all the [JSON parsing](https://github.com/lyft/beam/pull/48/files#diff-87b0c94c48274f394649ef3a123402f769b0743889a2902973a3675ad155e4bbR462) into a util method?

I believe the specific config options that will be added with https://jira.lyft.net/browse/STRMCMP-1126  could be folded into the `S3Config` class (which is re-used across `translateS3AndKinesisInputs` and `translateS3Inputs`).

**Comment by maghamravi** [comment]
> If I understand the recommendation correctly, it would imply`translateS3AndKinesisInputs` has a conditional check (maybe based on whether the `kinesisConfig` is passed or not) and keep `s3.py` as is?
> 
> I think that's a reasonable change and I'm open to making it. My concern with that is, we'll always be tightly coupled with the user config being the same for _just_ S3 and the bootstrapping usecase. Even though that's the current assumption in `translateS3Inputs` right now, we can choose to evolve our S3 source differently from the bootstrapping API usecase in the future if needed. So, my preference is to keep them separate and maybe we could make the code even more DRY by abstracting all the [JSON parsing](https://github.com/lyft/beam/pull/48/files#diff-87b0c94c48274f394649ef3a123402f769b0743889a2902973a3675ad155e4bbR462) into a util method?
> 
> I believe the specific config options that will be added with https://jira.lyft.net/browse/STRMCMP-1126 could be folded into the `S3Config` class (which is re-used across `translateS3AndKinesisInputs` and `translateS3Inputs`).

Agree to keep it as is keeping future evolution in mind.

**Pull request merged**
