### PR TITLE
Multikafka topics bugfix

### PR DESCRIPTION
**Pull request by maghamravi**
- Addresses a safety issue when we have multiple kafka consumer instances in a pipeline.  Does a lazy initialization to the kafka topics.

### CODE REVIEW

**Comment by premsantosh** [comment]
Sorry I don't understand. What happens if there are multiple kafka consumer instances?

**Comment by maghamravi** [comment]
From ex: [1] the beam pipeline had created 4 instances of Kafka Consumer. From the log within the Java code, we observe each instance  has the list of all the topics across 4 consumers.  On the surface, the earlier code looks benign. :)  

[1] https://kibana.lyft.net/app/discover/#/doc/cf3dd9e0-7305-11eb-bad9-93799307c46d/elasticlogsnt1:service-025924?id=015539f2-91a3-47e2-a554-ea0038dad6e0

**Comment by premsantosh** [comment]
But wouldn't you solve that by making the list a singleton? How is this change going to solve that issue? Sorry not trying to block you but I am unable to understand :)

**Review by sethsaperstein-lyft — APPROVED** [review]

**Comment by sethsaperstein-lyft** [comment]
> But wouldn't you solve that by making the list a singleton? How is this change going to solve that issue? Sorry not trying to block you but I am unable to understand :)

I believe multiple class instances are modifying the same static member variable list here. Very similar to the example given [here](https://discuss.codecademy.com/t/using-mutable-class-variables/512123/9). We actually want the opposite of a singleton I believe. One list per class instance.

**Comment by bhanuvikasr** [comment]
> > But wouldn't you solve that by making the list a singleton? How is this change going to solve that issue? Sorry not trying to block you but I am unable to understand :)
> 
> I believe multiple class instances are modifying the same static member variable list here. Very similar to the example given [here](https://discuss.codecademy.com/t/using-mutable-class-variables/512123/9). We actually want the opposite of a singleton I believe. One list per class instance.

The problem won't get fixed with this change since topics is still a static/class variable and multiple instances of `FlinkKafkaInput` are still accessing the same list object. 

I believe the correct way to fix this is to make topics an instance variable.

**Comment by premsantosh** [comment]
Got it! Thanks @sethsaperstein-lyft! And yes, agree with @bhanuvikasr

**Comment by maghamravi** [comment]
@bhanuvikasr you are spot on! Apparently, `topics` is a class variable and that introduced the issue.  I noticed it after @premsantosh asked his follow-up question earlier. Thanks for asking.

**Comment by maghamravi** [comment]
302 to https://github.com/lyft/beam/pull/62

**Pull request closed without merging**
